"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var classes_1 = require("./classes");
var car1 = new classes_1.Mitsubishi("Mirage", "001-QWE");
var car2 = new classes_1.Mitsubishi("Pajero", "002-WER");
var car3 = new classes_1.Mitsubishi("Mirage", "003-ERT");
var car4 = new classes_1.Mitsubishi("Pajero", "004-RTY");
var car5 = new classes_1.Mitsubishi("Xpander", "005-TYU");
var car6 = new classes_1.Toyota("Prius", "006-YUI");
var car7 = new classes_1.Toyota("Prius", "007-UIO");
var car8 = new classes_1.Toyota("Prius", "008-IOP");
var car9 = new classes_1.Toyota("Prius", "009-ASD");
var car10 = new classes_1.Toyota("Altis", "010-SDF");
var car11 = new classes_1.Toyota("Altis", "011-AZD");
var garage1 = new classes_1.Garage();
garage1.ParkCar(car1);
garage1.ParkCar(car2);
garage1.ParkCar(car3);
garage1.ParkCar(car4);
garage1.ParkCar(car5);
garage1.ParkCar(car6);
garage1.ParkCar(car7);
garage1.ParkCar(car8);
garage1.ParkCar(car9);
garage1.ParkCar(car10);
garage1.RemoveCar();
garage1.ParkCar(car2);
garage1.ParkCar(car11);
garage1.PrintAvailableSlots();
garage1.RemoveCar();
garage1.CarFilterByBrand("Mitsubishi").forEach(function (element) {
    console.log(element.plateNumber);
});
garage1.CarFilterByModel("Mirage").forEach(function (i) { return console.log(i.plateNumber); });
//garage1.PrintCars();
var GetFullName = function (firstName, lastName, middleName) {
    return middleName != null ? firstName + " " + middleName + " " + lastName : firstName + " " + lastName;
};
console.log(GetFullName("Jayson", "Concepcion", "Resmio"));
